import cron from 'node-cron';
import Customer from '../models/Customer.model.js';
import User from '../models/User.model.js';
import { createBulkNotifications } from './notificationService.js';

// Track last notification dates to prevent spam
const lastNotificationTracking = new Map();

// Function to check for missed follow-ups
const checkMissedFollowUps = async () => {
  try {
    console.log('🔍 Checking for missed follow-ups...');
    
    // Find customers with missed follow-ups
    const now = new Date();
    const missedFollowUps = await Customer.find({
      nextFollowUpDate: { $exists: true, $lt: now },
      status: { $ne: 'closed' }, // Don't check closed customers
      agentClosed: { $ne: true } // Don't check agent-closed customers
    }).populate('assignedAgent', 'name email');

    if (missedFollowUps.length === 0) {
      console.log('✅ No missed follow-ups found');
      return;
    }

    console.log(`⚠️ Found ${missedFollowUps.length} missed follow-ups`);

    // Get all super admins
    const superAdmins = await User.find({
      role: 'super_admin',
      isActive: true
    }).select('_id');

    if (superAdmins.length === 0) {
      console.log('❌ No super admins found to notify');
      return;
    }

    const superAdminIds = superAdmins.map(admin => admin._id);
    const notificationsToCreate = [];

    for (const customer of missedFollowUps) {
      const daysMissed = Math.floor((now - new Date(customer.nextFollowUpDate)) / (1000 * 60 * 60 * 24));
      const customerId = customer._id.toString();
      
      // Track last notification to prevent daily spam
      const lastNotified = lastNotificationTracking.get(customerId);
      const shouldNotify = !lastNotified || 
        (daysMissed >= 3 && !lastNotified.day3) ||
        (daysMissed >= 7 && !lastNotified.day7) ||
        (daysMissed >= 15 && !lastNotified.day15);

      if (shouldNotify && daysMissed >= 1) {
        // Determine priority based on days missed
        let priority = 'medium';
        if (daysMissed >= 7) priority = 'high';
        if (daysMissed >= 15) priority = 'urgent';

        const notificationData = {
          type: 'missed_followup_system',
          title: `⚠️ Follow-up Overdue - ${daysMissed} Day${daysMissed > 1 ? 's' : ''}`,
          message: `${customer.name} follow-up is ${daysMissed} day${daysMissed > 1 ? 's' : ''} overdue${customer.assignedAgent ? ` (Assigned: ${customer.assignedAgent.name})` : ' (Unassigned)'}`,
          priority,
          relatedEntity: {
            entityType: 'Customer',
            entityId: customer._id
          },
          actionUrl: `/dashboard/customers/${customer._id}`,
          metadata: {
            customerName: customer.name,
            daysMissed,
            assignedAgent: customer.assignedAgent?._id || null,
            assignedAgentName: customer.assignedAgent?.name || 'Unassigned',
            missedDate: customer.nextFollowUpDate,
            autoGenerated: true
          }
        };

        notificationsToCreate.push(...superAdminIds.map(adminId => ({
          recipient: adminId,
          ...notificationData
        })));

        // Update tracking
        const tracking = lastNotificationTracking.get(customerId) || {};
        if (daysMissed >= 3) tracking.day3 = true;
        if (daysMissed >= 7) tracking.day7 = true;
        if (daysMissed >= 15) tracking.day15 = true;
        lastNotificationTracking.set(customerId, tracking);
      }
    }

    if (notificationsToCreate.length > 0) {
      await createBulkNotifications(superAdminIds, notificationsToCreate[0]);
      console.log(`📧 Sent ${notificationsToCreate.length / superAdminIds.length} missed follow-up notifications to ${superAdminIds.length} super admin(s)`);
    }

  } catch (error) {
    console.error('❌ Error checking missed follow-ups:', error);
  }
};

// Function to start the follow-up checker
export const startFollowUpChecker = () => {
  console.log('🚀 Starting follow-up checker...');
  
  // Run every day at 9 AM
  cron.schedule('0 9 * * *', checkMissedFollowUps, {
    timezone: 'Asia/Dhaka'
  });
  
  // Run every 6 hours for critical follow-ups (optional)
  cron.schedule('0 */6 * * *', async () => {
    console.log('🔍 Quick check for critical missed follow-ups...');
    try {
      const now = new Date();
      const criticalMissed = await Customer.countDocuments({
        nextFollowUpDate: { 
          $exists: true, 
          $lt: new Date(now.getTime() - (7 * 24 * 60 * 60 * 1000)) // 7 days ago
        },
        status: { $ne: 'closed' },
        agentClosed: { $ne: true }
      });
      
      if (criticalMissed > 0) {
        console.log(`🚨 Found ${criticalMissed} critical missed follow-ups (7+ days)`);
        // Only run full check if there are critical ones
        await checkMissedFollowUps();
      }
    } catch (error) {
      console.error('Error in critical follow-up check:', error);
    }
  }, {
    timezone: 'Asia/Dhaka'
  });
  
  console.log('⏰ Follow-up checker scheduled to run daily at 9 AM (Asia/Dhaka time)');
};

// Function to manually trigger check (for testing)
export const triggerFollowUpCheck = checkMissedFollowUps;

export default {
  startFollowUpChecker,
  triggerFollowUpCheck
};